version: "3.2"
services:

  ivm_mysql:
    image: mysql:5.7
    container_name: 'ivm_mysql'
    ports:
      - "3320:3306"
    volumes:
      - ./volumes/lib:/var/lib/mysql
      - ./volumes/log:/var/log/mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=mylunacom
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=invest_master_docker

  ivm_java:
    image: alexpereira2004/ivm_java:v1.1
    container_name: 'ivm_java'
    command: ["java", "-jar", "/app.jar"]
    volumes:
      - ./target/portal-0.0.1-SNAPSHOT.jar:/app.jar
    depends_on:
      - ivm_mysql
    environment:
      DB_URL: jdbc:mysql://ivm_mysql:3306/invest_master_docker?useTimezone=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: mylunacom
    ports:
      - "8501:12001"
      - "8543:443"
    networks:
      - backend

  ivm_frontend:
    image: nginx:latest
    container_name: 'ivm_frontend'
    volumes:
      - D:/Desenv/Angular/InvestMasterFE/dist/invest-master-fe:/usr/share/nginx/html
    ports:
      - "4501:80"  # Porta padrão onde o Angular roda
    depends_on:
      - ivm_java  # Define que o frontend depende do backend estar em funcionamento
    environment:
      - BACKEND_URL=http://ivm_java:8501  # Defina a URL do backend
    networks:
      - backend

networks:
  backend:
    driver: bridge