INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('MMMC34','3M BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('ABTT34','Abbott Laboratories BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('ABBV34','Abbvie BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('ABCB4','ABC Brasil PN',NULL,'28195667000106',NULL,'A','https://br.investing.com/equities/abc-brasil-pn-ej-n2','S',NULL,NULL),
	 ('ACNB34','Accenture BDR',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL),
	 ('A1AP34','Advance Auto',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('ADHM3','Advanced-Dh ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('TIET2','Aes Tiete Energia Pref Rights',NULL,NULL,NULL,NULL,'https://br.investing.com/equities/aes-tiete-energia-pref-rights','N',NULL,NULL),
	 ('TIET3','AES Tiete ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/aes-tiete-on','N',NULL,NULL),
	 ('TIET4','AES Tiete PN',NULL,NULL,NULL,'A','https://br.investing.com/equities/aes-tiete-pn','N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('TIET11','AES Tiete Unit',NULL,NULL,NULL,'U','https://br.investing.com/equities/aes-tiete-energia-sa','N',NULL,NULL),
	 ('AFLT3','Afluente Transmissao de Energia',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('AIGB34','AIG BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('A1PD34','Air Products',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('A1KA34','Akamai Tech',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('A1LK34','Alaska Air',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('BRGE6','Alfa Administracao Pref',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('BRGE11','Alfa Administracao Pref E',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('BRGE12','Alfa Administracao Pref F',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('BRGE3','Alfa De Admin',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('BRGE5','Alfa De Admin A Pref',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('BRGE8','Alfa De Admin D Pref',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('RPAD3','Alfa Holdings ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('RPAD5','Alfa Holdings PNA',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('RPAD6','Alfa Holdings PNB',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('PEAB3','Alianca Bahia',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('PEAB4','Alianca da Bahia PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ALSO3','Aliansce Sonae',NULL,NULL,NULL,'A','https://br.investing.com/equities/aliansce-on-nm','S',NULL,NULL),
	 ('A1LG34','Align Tech',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('A1LL34','Alliance Data',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('AALR3','Alliar ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ALPA3','Alpargatas ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ALPA4','Alpargatas PN',NULL,NULL,NULL,'A','https://br.investing.com/equities/alpargatas-pn-n1','S',NULL,NULL),
	 ('GOGL34','Alphabet A BDR',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL),
	 ('GOGL35','Alphabet C BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('ALUP3','Alupar Invest ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ALUP4','Alupar Invest PN',NULL,'08364948000138',NULL,'A',NULL,'N',NULL,NULL),
	 ('ALUP11','Alupar Invest Unit',NULL,NULL,NULL,'U',NULL,'N',NULL,NULL),
	 ('AMZO34','Amazon.com BDR',NULL,NULL,NULL,'B','https://br.investing.com/equities/amazon.com-inc-bdr','S',NULL,NULL),
	 ('BAZA3','Amazonia ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('ABEV3','Ambev ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/ambev-pn','S',NULL,NULL),
	 ('AALL34','American Airlines BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('AXPB34','American Express BDR',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL),
	 ('AMGN34','Amgen BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('CBEE3','Ampla ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ANIM3','Anima ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('A1NT34','Anthem',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('AAPL34','Apple BDR',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL),
	 ('ARMT34','Arcelor Mittal BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('ARNC34','Arconic BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('ARZZ3','Arezzo ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ATOM3','Atompar ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ATTB34','ATT BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('AVON34','Avon Products BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('AZEV4','Azevedo & Travassos PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('AZEV3','Azevedo Travassos',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('AZUL4','Azul PN',NULL,'09305994000129',NULL,'A','https://br.investing.com/equities/azul-sa-pref','S',NULL,NULL),
	 ('BTOW3','B2W Digital ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/b2w-varejo-on-nm','S',NULL,NULL),
	 ('B3SA3','B3 ON',NULL,'09346601000125',NULL,'A','https://br.investing.com/equities/bmfbovespa-on-nm','S',NULL,NULL),
	 ('BAHI3','Bahema',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('ABCB10','Banco ABC Brasil',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('BRIV3','Banco Alfa ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('BRIV4','Banco Alfa PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('BMGB4','Banco BMG PN',NULL,NULL,NULL,'A',NULL,'S',NULL,NULL),
	 ('BPAC3','Banco BTG Pactual',NULL,'30306294000145',NULL,'A',NULL,'S',NULL,NULL),
	 ('BPAC5','Banco BTG Pactual Pref',NULL,'30306294000145',NULL,NULL,NULL,'N',NULL,NULL),
	 ('BBAS3','Banco do Brasil ON',NULL,'00000000000191',NULL,'A','https://br.investing.com/equities/brasil-on','S',NULL,NULL),
	 ('BGIP3','Banco do Estado de Sergipe',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('IDVL9','Banco Indusval',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('BIDI3','Banco Inter ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/banco-inter','S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('BIDI4','Banco Inter PN',NULL,NULL,NULL,'A','https://br.investing.com/equities/banco-inter-sa','S',NULL,NULL),
	 ('BIDI4T','Banco Inter PN Termo',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('BIDI11','Banco Inter Unit',NULL,NULL,NULL,'U','https://br.investing.com/equities/banco-inter-unt','S',NULL,NULL),
	 ('BMIN3','Banco Mercantil de Investimentos ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('BMEB3','Banco Mercantil do Brasil ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('BMEB4','Banco Mercantil do Brasil PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('BMIN4','Banco Mercantil PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('BPAN4','Banco Pan PN',NULL,NULL,NULL,'A','https://br.investing.com/equities/panamericano-pn','S',NULL,NULL),
	 ('BGIP4','Banese PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('BEES3','Banestes ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('BEES4','Banestes PN',NULL,'28127603000178',NULL,'A',NULL,'N',NULL,NULL),
	 ('BOAC34','Bank of America BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('BONY34','Bank of New York Mellon BDR',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL),
	 ('BRSR3','Banrisul ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('BRSR5','Banrisul PNA',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('BRSR6','Banrisul PNB',NULL,'92702067000196',NULL,'A','https://br.investing.com/equities/banrisul-pnb-n1','S',NULL,NULL),
	 ('BDLL4','Bardella PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('BARI11','Barigui Rendimento Imobiliários I',NULL,'29267567000100',NULL,'F',NULL,'S',NULL,NULL),
	 ('BTTL3','Battistella',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('BALM3','Baumer',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('BALM4','Baumer PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('BBIM11','BB Recebiveis Imobiliários',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('RDPD11','BB Renda de Papeis Imobiliários II',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('BBSE3','BB Seguridade ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/bbseguridad','S',NULL,NULL),
	 ('BERK34','Berkshire Hathaway BDR',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL),
	 ('BBYY34','Best Buy BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('BMKS3','Bicicletas Monark ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('BIIB34','Biogen BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('B1MR34','Biomarin',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('BIOM3','Biomm ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('BSEV3','Biosev ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('GBIO33','Biotoscana BDR',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('BLAK34','Blackrock BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('BLMO11','Bluemacaw Office',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('BNBR3','BNB ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('BOEI34','Boeing BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('BOBR4','Bombril PN',NULL,NULL,NULL,'A',NULL,'S',NULL,NULL),
	 ('BOXP34','Boston Properties BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('BBRK3','BR Brokers ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('APER3','BR Insurance Corretora ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('BRML3','BR Malls Par ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/br-malls-par-on-nm','S',NULL,NULL),
	 ('BPHA3','BR Pharma ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('BRPR3','BR Propert ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('BBDC3','Bradesco ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/bradesco-on-n1','S',NULL,NULL),
	 ('BBDC4','Bradesco PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('BRAP3','Bradespar ON',NULL,'03847461000192',NULL,'A',NULL,'N',NULL,NULL),
	 ('BRAP4','Bradespar PN',NULL,'03847461000192',NULL,'A','https://br.investing.com/equities/bradespar-pn-n1','S',NULL,NULL),
	 ('ELET5','Bras Eletrobr A Pref',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('BVAR11','Brasil Varejo',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('AGRO3','Brasilagro ON',NULL,'07628528000159',NULL,'A',NULL,'S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('BMII11','Brasilio Machado',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('BRKM3','Braskem ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('BRKM5','Braskem PN',NULL,NULL,NULL,NULL,'https://br.investing.com/equities/braskem-pna-n1','S',NULL,NULL),
	 ('BRKM6','Braskem Pref B',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('BZLI11','Brazil Realty',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('BSLI3','Brb Banco',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('BSLI4','BRB PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('BRCO11','Bresco Logistica',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('BRFS3','BRF ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/brf-foods-on-ej-nm','S',NULL,NULL),
	 ('ESTR4','Brinquedos Estrela PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('BMYB34','Bristol Myers Squibb BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('BRZP11','Brz Infra Portos',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('BPML11','Btg Pact Shp',NULL,'30306294000145',NULL,NULL,NULL,'N',NULL,NULL),
	 ('BTLG11','Btg Pactual',NULL,'30306294000145',NULL,NULL,NULL,'S',NULL,NULL),
	 ('BPAC11','BTG Pactual Unit',NULL,'30306294000145',NULL,'U','https://br.investing.com/equities/banco-btg-pactual-sa','S',NULL,NULL),
	 ('BKBR3','Burger King ON',NULL,NULL,NULL,'A',NULL,'S',NULL,NULL),
	 ('CEAB3','C&A Modas ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CAMB10','Cambuci Pref',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('CAMB3','Cambuci SA',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CAML3','Camil ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('CPFF11','Capitania',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('CRFB3','Carrefour ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/atacadao-sa','S',NULL,NULL),
	 ('CATP34','Caterpillar BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('C1BO34','Cboe Global',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('CCRO3','CCR ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/ccr-sa-on-nm','S',NULL,NULL),
	 ('CCXC3','CCX Carvao ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CEBR3','CEB ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CEDO3','Cedro Cachoeira ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CEDO4','Cedro PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CEED3','CEEE-D ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('EEEL3','CEEE-GT ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CLSC4','Celesc PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CLGN34','Celgene BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('GPAR3','Celgpar ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('EQPA5','Celpa PN',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('CEPE5','Celpe PN',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('RANI3','Celulose Irani ON',NULL,'92791243000103',NULL,'A',NULL,'N',NULL,NULL),
	 ('RANI4','Celulose Irani PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('MAPT3','Cemepe Investimentos ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('MAPT4','Cemepe Pref ',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('CMIG3','Cemig ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CMIG4','Cemig PN',NULL,NULL,NULL,'A','https://br.investing.com/equities/cemig-pn-n1','S',NULL,NULL),
	 ('CESP3','Cesp ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CESP5','Cesp PNA',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('CESP6','Cesp PNB',NULL,NULL,NULL,NULL,'https://br.investing.com/equities/cesp-pnb','S',NULL,NULL),
	 ('C1HR34','Ch Robinson',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('SCHW34','Charles Schwab BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('CHKE34','Chesapeake Energy BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('CHVX34','Chevron BDR',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL),
	 ('HGTX3','Cia Hering ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/cia-hering-on-nm','S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('CIEL3','Cielo ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/cielo-on-nm','S',NULL,NULL),
	 ('C1IC34','Cigna',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('CSCO34','Cisco Systems BDR',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL),
	 ('CTGP34','Citigroup BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('COCA34','Coca Cola BDR',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL),
	 ('CEEB3','Coelba ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CEEB5','Coelba PN',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('COCE3','Coelce ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('COCE5','Coelce PNA',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('COGN3','Cogna Educacao',NULL,'02800026000140',NULL,'A','https://br.investing.com/equities/kroton-on-nm','S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('CTSH34','Cognizant Tech BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('COLG34','Colgate Palmolive BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('CMCS34','Comcast BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('CGAS3','Comgas ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CGAS5','Comgas PNA',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('MSPA3','Companhia Melhoramentos ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CALI4','Con Ad Lin Pref',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('COPH34','ConocoPhillips BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('CSMG3','Copasa ON',NULL,'17281106000103',NULL,'A','https://br.investing.com/equities/copasa-on','S',NULL,NULL),
	 ('CPLE3','Copel ON',NULL,'04368898000106',NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('CPLE6','Copel PNB',NULL,'04368898000106',NULL,'A','https://br.investing.com/equities/copel-pnb','S',NULL,NULL),
	 ('CORR4','Correa Ribeiro',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('RLOG3','Cosan Log ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/cosan-logistica-sa','N',NULL,NULL),
	 ('CSAN3','Cosan ON',NULL,'50746577000115',NULL,'A','https://br.investing.com/equities/cosan-on-nm','S',NULL,NULL),
	 ('CSRN3','Cosern ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('COWC34','Costco Wholesale BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('CTNM3','Coteminas ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CTNM4','Coteminas PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('COTY34','Coty BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('CPFE3','CPFL Energia ON',NULL,'02429144000193',NULL,'A','https://br.investing.com/equities/cpfl-energia-on-nm','S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('CPRE3','CPFL Renovav ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CPRE3T','CPFL Renovaveis',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('CRDE3','CR2 ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CRPG3','Cristal Pigmentos',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CRPG5','Cristal Pigmentos PNA',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('CRPG6','Cristal Pigmentos PNB',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('HGFF11','CSHG Imobiliário FOF',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('CSNA3','CSN ON',NULL,'33042730000104',NULL,'A','https://br.investing.com/equities/sid-nacional-on','S',NULL,NULL),
	 ('CARD3','CSU Cardsyst ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('TRPL3','CTEEP ON',NULL,NULL,NULL,'A',NULL,'S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('TRPL4','CTEEP PN',NULL,NULL,NULL,'A','https://br.investing.com/equities/tran-paulist-pn','S',NULL,NULL),
	 ('CVCB3','CVC Brasil ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/cvc-brasil-on','S',NULL,NULL),
	 ('CVCB3T','CVC Viagens ON Termo',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('CVSH34','CVS Health BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('CCPR3','Cyre CCP ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CYRE3','Cyrela Realt ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/cyrela-realt-on-nm','S',NULL,NULL),
	 ('DHER34','Danaherrp BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('DASA3','Dasa ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CLSC3','De Santa Catar',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('DEAI34','Delta Air Lines BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('F1AN34','Diamondback',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('D1LR34','Digital Realty',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('PNVL3','Dimed ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/dimed-sa-distribuidora-de-medicamen','S',NULL,NULL),
	 ('PNVL4','Dimed PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('DIRR3','Direcional ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('D1FS34','Discover Fin',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('DOHL4','Dohler PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('DMMO11','Dommo Energia',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('DMMO3','Dommo ON',NULL,NULL,NULL,'A',NULL,'S',NULL,NULL),
	 ('DMMO3T','Dommo ON Termo',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('DTCY3','Dtcom BDR',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('D1TE34','Dte Energy',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('DUKB34','Duke Energy BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('DDNB34','DuPont Nemours',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('DTEX3','Duratex ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/duratex-on-nm','S',NULL,NULL),
	 ('EBAY34','Ebay BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('E1CL34','Ecolab',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('ECOR3','Ecorodovias ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/ecorodovias-on-nm','S',NULL,NULL),
	 ('ENBR3','EDP Brasil ON',NULL,'03983431000103',NULL,'A','https://br.investing.com/equities/energias-br-on','S',NULL,NULL),
	 ('EALT3','Electro Aco Altona',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('EALT4','Electro Aco Altona PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ELEK3','Elekeiroz ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ELEK4','Elekeiroz PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('EKTR4','Elektro PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('EKTR3','Eletric Servicos',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('EQPA6','Eletricas Para CELPA Pref B',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('LIPR3','Eletrobras Eletropar',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ELET3','Eletrobras ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/eletrobras-on','S',NULL,NULL),
	 ('ELET6','Eletrobras PNB',NULL,NULL,NULL,NULL,'https://br.investing.com/equities/eletrobras-pnb','S',NULL,NULL),
	 ('ELPL3','Eletropaulo ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('LILY34','Eli Lilly BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('EMAE4','EMAE PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('EMBR3','Embraer ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/embraer-on-nm','S',NULL,NULL),
	 ('ENAT3','Enauta ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ECPR3','Encorpar',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CEBR5','Energ De Brasilia A Pref',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('CEBR6','Energ De Brasilia B Pref',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('ENMT4','Energisa Mato Grosso',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ENMT3','Energisa MT ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ENGI3','Energisa ON',NULL,NULL,NULL,'A',NULL,'S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('ENGI4','Energisa PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ENGI11','Energisa Unit',NULL,NULL,NULL,'U','https://br.investing.com/equities/energisa-sa','S',NULL,NULL),
	 ('ENEV3','Eneva ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/eneva-sa','S',NULL,NULL),
	 ('EGIE3','Engie Brasil ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/tractebel-on-nm','S',NULL,NULL),
	 ('EQTL3','Equatorial ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/equatorial-on-nm','S',NULL,NULL),
	 ('EQPA3','Equatorial Para Distribuidora de Energia SA',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('EQPA7','Equatorial Para Distribuidora Enrg',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('EEEL4','Estadual Geracao Transmissao',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ETER3','Eternit ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('EUCA3','Eucatex',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('EUCA4','Eucatex PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ERPA11','Europa 105',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('EVEN3','Even ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('KINP11','Even Permuta Kinea',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('E1VR34','Evergy',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('E1SE34','Eversource',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('BAUH4','Excelsior Alimentos PN',NULL,NULL,NULL,'A',NULL,'S',NULL,NULL),
	 ('EXXO34','Exxon Mobil BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('EZTC3','Eztec ON',NULL,'08312229000173',NULL,'A','https://br.investing.com/equities/eztec-on-nm','S',NULL,NULL),
	 ('FBOK34','Facebook BDR',NULL,NULL,NULL,'B','https://br.investing.com/equities/facebook-inc-bdr','S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('FDXB34','Fedex BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('FHER3','Fer Heringer ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('FESA3','Ferbasa ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('FESA4','Ferbasa PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('VSPT3','Ferrovia Centro Atlantica ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('VTLT11','FI Imobiliario Votorantim Logistica',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('VSHO11','FI Imobiliario Votorantim Shopping',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('FPAB11','FII A Branca',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('ABCP11','FII Abc Imob',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('BPFF11','FII Absoluto',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('RBED11','FII Aesapar',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('ALZR11','FII Alianza',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('FAED11','FII Anh Educ',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('ATSA11','FII Atrium Shopping Santo Andre',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('BNFS11','FII Banrisul',NULL,'15570431000160',NULL,'F',NULL,'N',NULL,NULL),
	 ('BBRC11','FII BB Corp',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('BBPO11','FII BB Prgii',NULL,'14410722000129',NULL,'F','https://br.investing.com/equities/fii-bb-prgii','S',NULL,NULL),
	 ('RNDP11','FII BB R Pap',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('BCFF11','FII Bc FFII Ci',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('BRCR11','FII Bc Fund',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('BCIA11','FII Bcia',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('BCRI11','FII Bees Cri',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('THRA11','FII BM Thera',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('BREV11','Fii Bre Vic',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('BPRP11','FII BRLPROP',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('BTCR11','FII BTG PACTUAL CREDITO IMOBILIARIO',NULL,'30306294000145',NULL,'F',NULL,'N',NULL,NULL),
	 ('CBOP11','FII C Branco',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('BBVJ11','FII C Jardim',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('CTXT11','FII C Textil',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('FCFL11','FII Campusfl',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('CNES11','Fii Cenesp',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('CEOC11','FII Ceo Ccp',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('HCRI11','FII Crianca',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('HGCR11','FII CSHG Cri',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('HGLG11','FII CSHG Log',NULL,'11728688000147',NULL,'F',NULL,'N',NULL,NULL),
	 ('HGRU11','FII CSHG Urb',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('HGPO11','FII Cshgjhsf',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('HGBS11','FII Cshgshopci Er',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('CXRI11','FII Cx Rbrav',NULL,'17098794000170',NULL,'F','https://br.investing.com/equities/fii-caixa-rio-bravo','N',NULL,NULL),
	 ('CXTL11','FII Cx Trx',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('PQDP11','FII D Pedro',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('CARE11','FII Dea Care',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('DOMC11','FII Domo',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('EURO11','FII Europar',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('FEXC11','FII Excellence',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('VRTA11','FII Fator Ve',NULL,'11664201000100',NULL,'F','https://br.investing.com/equities/fii-fator-ve','S',NULL,NULL),
	 ('FLRP11','FII Floripa',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('EDGA11','FII Galeria',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('FIGS11','FII Gen Shop',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('GGRC11','FII Ggr Covepi',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('GTWR11','FII Green Towers',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('HABT11','FII HABIT II',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('HMOC11','FII Hedmoca',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('HGRE11','FII HG Real',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('SHPH11','FII Higienop',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('HTMX11','FII Hotel Mx',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('HOSI11','Fii Housi',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('FOFT11','FII Htopfof2',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('HFOF11','FII Htopfof3',NULL,'18307582000119',NULL,'F','https://br.investing.com/equities/hedge-top-fofii-3-fii','S',NULL,NULL),
	 ('FIIB11','FII Indl Br',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('RBBV11','FII Jhsf Fbv',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('JSRE11','FII Js Real',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('KNRE11','FII Kii Real',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('KNRI11','FII Kinea',NULL,NULL,NULL,'F',NULL,'S',NULL,NULL),
	 ('KNHY11','FII Kinea Hy',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('KNCR11','FII Kinea Ri',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('NSLU11','FII Lourdes',NULL,'08014513000163',NULL,'F','https://br.investing.com/equities/fii-nossa-senhora-de-lourdes','N',NULL,NULL),
	 ('GRLV11','FII Louveira',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('MCCI11','Fii Maua Capital',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('MAXR11','FII Max Ret',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('MXRF11','FII Maxi Ren',NULL,'97521225000125',NULL,'F','https://br.investing.com/equities/fii-maxi-ren','S',NULL,NULL),
	 ('FMOF11','FII Memorial',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('MBRF11','FII Merc Br',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('MFII11','FII Merito',NULL,'16915968000188',NULL,'F','https://br.investing.com/equities/fundo-investimento-imobil-merito','S',NULL,NULL),
	 ('MGFF11','FII Mogno',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('VLOL11','FII Olimpia',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('OUJP11','FII Ouri Jpp',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('OUCY11','FII Ouricyre',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('PRSV11','FII P Vargas',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('PABY11','FII Panamby',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('PORD11','FII Polo Cri',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('PLRI11','FII Polo I',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('RFOF11','Fii Rb Capital I',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('RBGS11','FII Rb Gsb I',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('RBRD11','FII Rb II',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('RBRF11','FII Rbralpha',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('RBDS11','FII Rbresid2',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('RBRR11','FII Rbrhgrad',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('RCRB11','FII Rio Bravo Renda Corporativa',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('RBVA11','FII Rio Bravo Rendo Varejo',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('RBVO11','FII Riobcri2',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('RBCB11','FII Riobrcib',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('RNGO11','FII Rionegro',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('FLMA11','FII S F Lima',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('SAAG11','FII Sant Age',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('SARE11','Fii Sant Ren',NULL,'32903702000171',NULL,'F',NULL,'N',NULL,NULL),
	 ('SCPF11','FII Scp',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('SDIL11','FII Sdi Log',NULL,'16671412000193',NULL,'F','https://br.investing.com/equities/fii-sdi-log','N',NULL,NULL),
	 ('JRDM11','FII Shopjsul',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('SPTW11','FII Sp Downt',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('TBOF11','FII Tboffice',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('TGAR11','FII Tg Ativo',NULL,'25032881000153',NULL,'F','https://br.investing.com/equities/fii-tg-ativo-real','S',NULL,NULL),
	 ('ONEF11','FII The One',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('ALMI11','FII Torre Al',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('TRNT11','FII Torre No',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('TRXF11','Fii Trx Real',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('XTED11','FII Trxe Cor',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('RECT11','FII UBS (BR) OFFICE',NULL,NULL,NULL,'F','https://br.investing.com/equities/fii-ubs-(br)-office','S',NULL,NULL),
	 ('FVPQ11','FII V Parque',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('FVBI11','FII Vbi 4440',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('RVBI11','Fii Vbi Reit',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('FIVN11','FII Vidanova',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('VISC11','FII Vinci Sc',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('XPIN11','FII XP Indl',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('XPCM11','FII XP Macae',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('FNAM11','Finam CI',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('CRIV3','Financeira Alfa ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CRIV4','Financeira Alfa PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('FNOR11','Finor',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('ESUD11','FIP Infra Estr BB Votorantim II A',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('ESUT11','FIP Infra Estr BB Votorantim III A',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('PFIN11','Fip Perfin',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('XPOM11','FIP XP Omega I',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('FSLR34','First Solar BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('FSRF11','Fiset FL Ref CI',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('FSPE11','FISET FL REF PRF',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('FSTU11','Fiset Tur CI',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('FLRY3','Fleury ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/fleury-on-nm','S',NULL,NULL),
	 ('FMXB34','Fomento Economico Mexicano BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('FDMO34','Ford Motor BDR',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('FRAS3','Fras-Le ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('FCXO34','Freeport Mcmoranpper Gold BDR',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL),
	 ('WPLZ11','Fundo Inves',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('ANIM3T','Gaec Educacao ON Termo',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('GFSA1','Gafisa',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('GFSA3','Gafisa ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('GPSI34','Gap BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('GDBR34','General Dynamicsrp BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('GEOO34','General Electric BDR',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL),
	 ('GMCO34','General Motors BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('HBTT11','General Severiano',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('GSHP3','General Shopping ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('GEPA4','Ger Paranapanema PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('GGBR3','Gerdau ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('GGBR4','Gerdau PN',NULL,'33611500000119',NULL,'A','https://br.investing.com/equities/gerdau-pn-n1','S',NULL,NULL),
	 ('GILD34','Gilead Sciences BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('GOLL4','Gol PN',NULL,'06164253000187',NULL,'A','https://br.investing.com/equities/gol-pn-es-n2','S',NULL,NULL),
	 ('GSGI34','Goldmanchs Group BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('GPRO34','GoPro BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('GPIV33','GP Invest BDR A',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('GPCP3','GPC Part ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CGRA3','Grazziotin ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CGRA4','Grazziotin PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('GRND3','Grendene ON',NULL,'89850341000160',NULL,'A','https://br.investing.com/equities/grendene-on-nm','S',NULL,NULL),
	 ('RCFA11','Grupo RCFA',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('CNTO3','Grupo SBF Centauro',NULL,NULL,NULL,'A','https://br.investing.com/equities/grupo-sbf-sa','N',NULL,NULL),
	 ('GUAR3','Guararapes ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('HBTS5','Habitasul PN',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('HAGA3','Haga Industria Comercio',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('HAGA4','Haga PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('HALI34','Halliburton BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('HAPV3','Hapvida ON',NULL,'05197443000138',NULL,'A','https://br.investing.com/equities/hapvida-participacoes-investimentos','S',NULL,NULL),
	 ('ATCR11','HAZ',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('HCTR11','Hectare Ce Fdo Inv Imob',NULL,'30248180000196',NULL,'F','https://br.investing.com/equities/hectare-ce-fdo-inv-imob-reit','S',NULL,NULL),
	 ('HLOG11','Hedge Logistica',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('HRDF11','Hedge Realty',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('HPDP11','Hedge Shopping',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('TFOF11','Hedge Top FOFII',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('HBOR3','Helbor ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('HETA4','Hercules PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('PARD3','Hermes Pardini ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('HSHY34','Hershey BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('HPQB34','Hewlett Packard BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('HOME34','Home Depot BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('HONB34','Honeywell BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('HUSC11','Hospital Unimed Sul Capixaba',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('HOOT4','Hoteis Othon PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('HSML11','HSI Malls FII',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('HUSI11','Husi Fundo',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('HYPE3','Hypera ON',NULL,'02932074000191',NULL,'A','https://br.investing.com/equities/hypermarcas-on-nm','S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('IBMB34','IBM BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('IDNT3','Ideiasnet ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('IGBR3','IGB ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('IGTA3','Iguatemi ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/iguatemi-on-nm','S',NULL,NULL),
	 ('I1NF34','Ihs Markit',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('MEAL3','IMC ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ROMI3','Inds Romi ON',NULL,'56720428000163',NULL,'A',NULL,'S',NULL,NULL),
	 ('JBDU1','Industrias JB Duarte Right 1',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('JBDU2','Industrias JB Duarte Right 2',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('IDVL3','Indusval ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('IDVL4','Indusval PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('INEP3','Inepar ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('INEP4','Inepar PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('FINF11','Infra Real State',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('IBFF11','Integral Brei Reit',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('ITLC34','Intel BDR',NULL,'00997185000150',NULL,'B',NULL,'S',NULL,NULL),
	 ('BICR11','Inter Titulos',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('GNDI3','Intermedica ON',NULL,'19853511000184',NULL,'A','https://br.investing.com/equities/notre-dame-intermedica-participacoe','S',NULL,NULL),
	 ('I1FF34','International Flavors',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('MYPK3','Iochpe-Maxion ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/iochp-maxion-on-nm','S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('IRBR3','IRB Brasil ON',NULL,'33376989000191',NULL,'A','https://br.investing.com/equities/irb-brasil-resseguros','S',NULL,NULL),
	 ('IRDM11','Iridium Recebíveis Imob',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('ITUB3','Itau Unibanco ON',NULL,'60701190000104',NULL,'A','https://br.investing.com/equities/itauunibanco-on-edj-n1','S',NULL,NULL),
	 ('ITUB4','Itau Unibanco PN',NULL,'60701190000104',NULL,'A','https://br.investing.com/equities/itauunibanco-pn-edj-n1','S',NULL,NULL),
	 ('ITSA3','Itausa ON',NULL,'61532644000115',NULL,'A','https://br.investing.com/equities/itausa-on-ej-n1','S',NULL,NULL),
	 ('ITSA4','Itausa PN',NULL,'61532644000115',NULL,'A','https://br.investing.com/equities/itausa-pn-ej-n1','S',NULL,NULL),
	 ('ITEC3','Itautec',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('JBDU3','J B Duarte ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('JBDU4','J B Duarte PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('JCPC34','J C Penney BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('JBSS3','JBS ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/jbs-on-nm','S',NULL,NULL),
	 ('J1EF34','Jefferies Fin',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('JPSA3','Jereissati Part ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('JHSF3','JHSF Part ON',NULL,'08294224000165',NULL,'A','https://br.investing.com/equities/jhsf-part-on-nm','S',NULL,NULL),
	 ('JFEN3','Joao Fortes ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('JNJB34','Johnson Johnson BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('JOPA3','Josapar ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('JOPA4','Josapar PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('JPMC34','JP Morgan Chase BDR',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL),
	 ('JPPA11','Jpp Allocation',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('JPPC11','JPP Capital',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('JSLG3','JSL ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CTKA3','Karsten',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CTKA4','Karsten PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('K1EL34','Kellogg',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('KEPL11','Kepler Weber',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('KEPL3','Kepler Weber ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('KMBB34','Kimberly Clarkrp BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('KNIP11','Kinea Índice de Preços FDO INV IMOB - FII',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('KLBN3','Klabin ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/klabin-sa','S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('KLBN4','Klabin PN',NULL,'89637490000145',NULL,'A','https://br.investing.com/equities/klabin-s-a-pn-n1','S',NULL,NULL),
	 ('KLBN11','Klabin Unit',NULL,NULL,NULL,'U','https://br.investing.com/equities/klabin-unt','S',NULL,NULL),
	 ('KHCB34','Kraft Heinz BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('LBRN34','L Brands BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('L1RC34','Lam Res',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('LLIS3','Le Lis Blanc ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('LMED3','Lifemed',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('LIGT3','Light ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/light-s-a-on-nm','S',NULL,NULL),
	 ('L1IN34','Linde',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('LINX3','Linx ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/linx-on','S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('ATMP3','Liq ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('L1KQ34','Lkq',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('RENT3','Localiza ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/localiza-on-ej-nm','S',NULL,NULL),
	 ('LCAM3','Locamerica ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/companhia-de-locacao-das-americas','S',NULL,NULL),
	 ('LWSA3','Locaweb On',NULL,'02351877000152',NULL,'A','https://br.investing.com/equities/locaweb-servicos-de-internet-sa','S',NULL,NULL),
	 ('LMTB34','Lockheed Martin BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('LOGG3','Log CP ON',NULL,NULL,NULL,'A',NULL,'S',NULL,NULL),
	 ('LOGN12','Log-in Logistica Right',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('LOGN3','Log-In ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('LGCP11','Logcp Inter Fundo',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('LAME3','Lojas Americanas ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('LAME4','Lojas Americanas PN',NULL,NULL,NULL,'A','https://br.investing.com/equities/lojas-americ-pn-int','S',NULL,NULL),
	 ('AMAR3','Lojas Marisa ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('LREN3','Lojas Renner ON',NULL,'92754738000162',NULL,'A','https://br.investing.com/equities/lojas-renner-on-nm','S',NULL,NULL),
	 ('LPSB3','Lopes Brasil ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('LUGG11','Luggo Fundo',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('L1UL34','Lululemon',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('LUPA3','Lupatech ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('MDIA3','M.Dias Branco ON',NULL,'07206816000115',NULL,'A','https://br.investing.com/equities/m.diasbranco-on-ej-nm','S',NULL,NULL),
	 ('DMAC11','MAC Fundo de Investimento Imobiliario',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('MACY34','Macy’s BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('MGLU3','Magazine Luiza ON',NULL,'47960950000121',NULL,'A','https://br.investing.com/equities/magaz-luiza-on-nm','S',NULL,NULL),
	 ('MGEL4','Mangels PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('POMO3','Marcopolo ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('POMO4','Marcopolo PN',NULL,NULL,NULL,'A','https://br.investing.com/equities/marcopolo-pn-n2','S',NULL,NULL),
	 ('POMO10','Marcopolo PRF',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('MRFG3','Marfrig ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/marfrig-on-nm','S',NULL,NULL),
	 ('M1TT34','Marriott',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('MSCD34','Mastercard BDR',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL),
	 ('M1KC34','Mccormick',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('MCDC34','McDonalds BDR',NULL,'00997185000150',NULL,'B','https://br.investing.com/equities/mcdonalds-corp-bdr','S',NULL,NULL),
	 ('BDLL3','Mecanicas',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('MDTC34','Medtronic BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('MSPA4','Melhor Pref ',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('MEND6','Mendes Junior',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('MEND5','Mendes Junior PNA',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('MELI34','Mercadolibre BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('MERC4','Mercantil Brasil Financeira',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('MRCK34','Merck BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('GOAU3','Met. Gerdau ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('GOAU4','Met. Gerdau PN',NULL,'92690783000109',NULL,'A','https://br.investing.com/equities/gerdau-met-pn','S',NULL,NULL),
	 ('MTIG4','Metal Iguacu PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('LEVE3','Metal Leve ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/metal-leve-on-ej-nm','S',NULL,NULL),
	 ('FRIO3','Metalfrio ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('RSUL4','Metalurgica Riosulense',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('MTSA4','Metisa PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('MTSA3','Metisa Metalg Tim',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('METB34','Metlife BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('MSFT34','Microsoftrp BDR',NULL,NULL,NULL,'B','https://br.investing.com/equities/microsoft-corp-bdr','S',NULL,NULL),
	 ('MILS3','Mills ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('BEEF11','Minerva',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('BEEF3','Minerva ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/minerva-on-nm','S',NULL,NULL),
	 ('MNPR3','Minupar Part ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('MTRE3','Mitre Realty On',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('MMXM3','MMX ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('MMXM11','MMX TPR',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('MDLZ34','Mondelez International BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('M1NS34','Monster Beverage',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('MOAR3','Monteiro Aranha',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('MSBR34','Morgan Stanley Bank BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('MOSC34','Mosaic Company BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('MDNE3','Moura Dubeux On',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('MOVI3','Movida ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/movida-participacoes-sa','S',NULL,NULL),
	 ('MRVE3','MRV ON',NULL,'08343492002335',NULL,'A','https://br.investing.com/equities/mrv-on-nm','S',NULL,NULL),
	 ('PRTS11','Multi Properties',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('SHOP11','Multi Shoppings',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('MULT3','Multiplan ON',NULL,'07816890000153',NULL,'A','https://br.investing.com/equities/multiplan-on-n2','S',NULL,NULL),
	 ('MNDL3','Mundial ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('NAFG3','Nadir Figueiredo',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('N1OV34','National Oilwell',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('NTCO3','Natura ON',NULL,'71673990000177',NULL,'A','https://br.investing.com/equities/natura-on-nm','S',NULL,NULL),
	 ('NCHB11','NCH Brasil Recebíveis Imobiliários',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('NEOE3','Neoenergia ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/neoenergia','S',NULL,NULL),
	 ('NPAR11','Nestpar',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('NFLX34','Netflix BDR',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL),
	 ('NEWL11','Newport Logistica',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('NEWU11','Newport Renda Urbana',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('N1WS34','News',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('NIKE34','Nike BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('NORD3','Nordon Metalg',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('CSRN5','Norte Cosern A Pref',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('CSRN6','Norte Cosern B Pref',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('NVHO11','Novo Horizonte',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('NUTR3','Nutriplant ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ODPV3','Odontoprev ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/odontoprev-on-ej-nm','S',NULL,NULL),
	 ('OIBR3','Oi ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/brasil-telec-on','S',NULL,NULL),
	 ('OIBR4','Oi PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('OMGE3','Omega Ger ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ORCL34','Oracle BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('OSXB3','OSX Brasil ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('OFSA3','Ouro Fino ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ORPD11','Ouro Preto Desenvolvimento Imobiliário I',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('PATI3','Panatlantica',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('PATI4','Panatlantica PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('PMAM3','Paranapanema ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('PATC11','Patria Edifícios Corporativos FII',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('PDGR3','PDG Realt ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('FPNG11','Pedra Negra Renda Imobiliária',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('PEPB34','Pepsico BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('BRDT3','Petrobras Distr ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/petrobras-distribuidora','S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('PETR3','Petrobras ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/petrobras-on','S',NULL,NULL),
	 ('PETR4','Petrobras PN',NULL,'33000167000101',NULL,'A','https://br.investing.com/equities/petrobras-pn','S',NULL,NULL),
	 ('PRIO3','Petrorio ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/hrt-petroleo-on-nm','S',NULL,NULL),
	 ('RPMG3','Petróleo Manguinhos ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('PTNT4','Pettenati PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('PFIZ34','Pfizer BDR',NULL,NULL,NULL,'B','https://br.investing.com/equities/pfizer-inc-bdr','S',NULL,NULL),
	 ('PINE4','Pine PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('P1IO34','Pioneer Natural',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('PLAS3','Plascar Part ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('PLCR11','Plural Recebiveis',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('VPSI11','Polo Shopping Indaiatuba',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('FRTA3','Pomifrutas ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('PSSA3','Porto Seguro ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/porto-seguro-on-ej-nm','S',NULL,NULL),
	 ('PSVM11','Porto Sudeste',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('PTBL3','Portobello ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('POSI3','Positivo Inf ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('PPLA11','PPLA Unit',NULL,NULL,NULL,'U',NULL,'N',NULL,NULL),
	 ('PRNR3','Priner Servicos Industriais SA',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('PGCO34','Procter Gamble BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('PFRM3','Profarma ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/profarma-on-nm','S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('PBLV11','Prologis Brazil Logistics Venture',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('P1DT34','Prudential',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('PCAR3','Pão de Açúcar CBD ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/companhia-brasileira-de-distribuica','S',NULL,NULL),
	 ('QCOM34','Qualcomm BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('QUAL3','Qualicorp ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/qualicorp-on-nm','S',NULL,NULL),
	 ('QAGR11','Quasar Agro',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('RADL3','Raia Drogasil ON',NULL,' 61585865000151',NULL,'A','https://br.investing.com/equities/raiadrogasil-on-nm','S',NULL,NULL),
	 ('RAPT3','Randon Part ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('RAPT4','Randon Part PN',NULL,NULL,NULL,'A','https://br.investing.com/equities/randon-part-pn-n1','S',NULL,NULL),
	 ('RBCO11','Rb Cap',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('RSPD11','Rb Cap',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('RBTS11','Rb Capital',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('RBRY11','RBR Private Crédito Imobiliário',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('RBRP11','RBR Properties',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('RCSL3','Recrusul ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('RCSL4','Recrusul PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('REDE3','Rede Energia ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('ARRI11','Reit Recebiveis',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('RNEW3','Renova ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('RNEW4','Renova PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('RNEW11','Renova Unit',NULL,NULL,NULL,'U',NULL,'N',NULL,NULL),
	 ('R1SG34','Republic Services',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('RBIV11','Rio Bravo Credito',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('RBFF11','Rio Bravo IFIX',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('GEPA3','Rio Paranapanema Energia ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('RDNI3','Rodobens ON',NULL,NULL,NULL,'A',NULL,'S',NULL,NULL),
	 ('ROST34','Ross Stores BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('RSID3','Rossi Resid ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('R1CL34','Royal Caribbean',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('RAIL3','Rumo ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/all-amer-lat-on-nm','S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('SPGI34','S And P Global',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('SBSP3','Sabesp ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/sabesp-on','S',NULL,NULL),
	 ('SSFO34','Salesforce.com BDR',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL),
	 ('SANC34','Sanchez Energy BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('SAPR3','Sanepar ON',NULL,' 76484013000145',NULL,'A','https://br.investing.com/equities/sanepar-on-n2','N',NULL,NULL),
	 ('SAPR4','Sanepar PN',NULL,' 76484013000145',NULL,'A','https://br.investing.com/equities/companhia-de-saneamento-do-parana-s','N',NULL,NULL),
	 ('SAPR11','Sanepar Unit',NULL,' 76484013000145',NULL,'U','https://br.investing.com/equities/parana-sanepar-unit','S',NULL,NULL),
	 ('SNSY5','Sansuy PNB',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('SANB3','Santander Brasil ON ',NULL,' 90400888000142',NULL,'A',NULL,'N',NULL,NULL),
	 ('SANB4','Santander Brasil PN ',NULL,' 90400888000142',NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('SANB11','Santander Brasil Unit',NULL,' 90400888000142',NULL,'U','https://br.investing.com/equities/santander-br-unt-ed-n2','S',NULL,NULL),
	 ('SADI11','Santander Papeis Imobiliários CDI',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('CTSA3','Santanense ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CTSA4','Santanense PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('STBP3','Santos Brasil ON',NULL,'02762121000104',NULL,'A',NULL,'N',NULL,NULL),
	 ('SCAR3','Sao Carlos ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('SMTO3','Sao Martinho ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('AHEB3','Sao Paulo Turismo',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('SLED3','Saraiva ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('SLED4','Saraiva PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('SLED2','Saraiva PN',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('FISC11','SC 401',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('SLBG34','Schlumberger BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('SHUL4','Schulz PN',NULL,NULL,NULL,'A',NULL,'S',NULL,NULL),
	 ('SDIP11','SDI Properties',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('CSAB3','Seguros Alianca',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('CSAB4','Seguros Alianca Pref',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('SEER3','Ser Educacional ON',NULL,NULL,NULL,'A',NULL,'S',NULL,NULL),
	 ('SEER3T','Ser Educacional ON Termo',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('SQIA3','Sinqia ON',NULL,' 04065791000199',NULL,'A','https://br.investing.com/equities/senior-sol','S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('SLCE3','SLC Agricola ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/slc-agricola-on-nm','S',NULL,NULL),
	 ('SMLS3','Smiles ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/smiles-on','S',NULL,NULL),
	 ('SMLS3T','Smiles PN',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('REIT11','Socopa Fundo de Investimento Imobiliário',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('SEDU3','Somos Educacao ON ',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('SOND5','Sondotecnica PNA',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('SOND6','Sondotecnica PNB',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('SPAF11','SPA Fundo de Investimento Imobiliário',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('SPRI5','Springer A Pref',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('SPRI6','Springer B Pref',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('SPRI3','Springer ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('SGPS3','Springs ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('SPRN34','Sprint BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('SBUB34','Starbucks BDR',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL),
	 ('STRX11','STARX FII',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('SULA4','Sul America',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('SULA3','Sul America Pref',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('SULA11','Sul America Unit',NULL,'29978814000187',NULL,'U','https://br.investing.com/equities/sul-america-unt-n2','S',NULL,NULL),
	 ('SUZB3','Suzano Papel ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/suzano-papel-celulose','S',NULL,NULL),
	 ('FISD11','São Domingos',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('SFND11','São Fernando',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('TAEE3','Taesa ON',NULL,' 07859971000130',NULL,'A','https://br.investing.com/equities/taee-3','S',NULL,NULL),
	 ('TAEE4','Taesa PN',NULL,' 07859971000130',NULL,'A','https://br.investing.com/equities/taee-pref','S',NULL,NULL),
	 ('TAEE11','Taesa Unit',NULL,' 07859971000130',NULL,'U','https://br.investing.com/equities/taesa-unt-n2','S',NULL,NULL),
	 ('T1TW34','Take Two Interactive',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('TGTB34','Target BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('TRPN3','Tarpon ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('TASA13','Taurus Armas Bônus de Subscrição B',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('TASA15','Taurus Armas Bônus de Subscrição C',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('TASA17','Taurus Armas Bônus de Subscrição D',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('TASA3','Taurus Armas ON',NULL,NULL,NULL,'A',NULL,'S',NULL,NULL),
	 ('TASA4','Taurus Armas PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('T1EC34','Technipfmc',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('TECN3','Technos ON',NULL,NULL,NULL,'A',NULL,'S',NULL,NULL),
	 ('TCSA3','Tecnisa ON',NULL,'08065557000112',NULL,'A','https://br.investing.com/equities/tecnisa-on-nm','S',NULL,NULL),
	 ('TCNO3','Tecnosolo ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('TCNO4','Tecnosolo PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('TOYB3','Tectoy ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('TOYB4','Tectoy PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('TGMA3','Tegma ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('TEKA4','Teka PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('TEKA3','Teka Tecelagem',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('TKNO4','Tekno Pref',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('TELB3','Telebras ON',NULL,NULL,NULL,'A',NULL,'S',NULL,NULL),
	 ('TELB4','Telebras PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('VIVT3','Telefonica Brasil ON',NULL,'02558157000162',NULL,'A',NULL,'N',NULL,NULL),
	 ('VIVT4','Telefonica Brasil PN',NULL,NULL,NULL,'A','https://br.investing.com/equities/telef-brasil-pn','N',NULL,NULL),
	 ('TEND3','Tenda ON',NULL,'71476527000135',NULL,'A',NULL,'S',NULL,NULL),
	 ('TESA3','Terra Santa ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('TSLA34','Tesla Motors BDR',NULL,NULL,NULL,'B','https://br.investing.com/equities/tesla-motors-inc-drc','S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('TEXA34','Texas Instruments BDR',NULL,'60746948000112',NULL,'B',NULL,'S',NULL,NULL),
	 ('TXRX4','Textil Renauxview PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('P1GR34','The Progressive',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('TMOS34','Thermo Fisher Scientific',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('TIFF34','Tiffany BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('TIMP3','TIM ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/tim-part-s-a-on-nm','N',NULL,NULL),
	 ('SHOW3','Time For Fun ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('TORD11','Tordesilhas EI',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('TOTS3','Totvs ON',NULL,'53113791000122',NULL,'A','https://br.investing.com/equities/totvs-on-ej-nm','S',NULL,NULL),
	 ('TORM13','Tourmalet I',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('TOUR11','Tourmalet II',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('I1RP34','Trane Tech',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('T1DG34','Transdigm',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('TSNC11','Transinc',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('RIGG34','Transocean BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('TRVC34','Travelers Companies BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('TCPF11','Treecorp',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('LUXM4','Trevisa Invest',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('TRIS3','Trisul ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('TPIS3','Triunfo ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('TUPY3','Tupy ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/tupy-on','S',NULL,NULL),
	 ('TWTR34','Twitter BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('USBC34','U.S. Bancorp BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('UBSG34','UBS BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('UGPA3','Ultrapar ON',NULL,'33256439000139',NULL,'A','https://br.investing.com/equities/ultrapar-on-nm','S',NULL,NULL),
	 ('U1AI34','Under Armour',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('UCAS3','Unicasa ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('UPAC34','Union Pacific BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('UNIP3','Unipar ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/unipar-on-n1','S',NULL,NULL),
	 ('UNIP5','Unipar PNA',NULL,NULL,NULL,NULL,'https://br.investing.com/equities/unipar-carbocloro-sa','S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('UNIP6','Unipar PNB',NULL,NULL,NULL,NULL,'https://br.investing.com/equities/unipar-pnb-n1','S',NULL,NULL),
	 ('UPSS34','United Parcel Service BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('USSX34','United States Steel BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('UTEC34','United Technologiesrp BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('USIM3','Usiminas ON',NULL,'60894730000105',NULL,'A',NULL,'N',NULL,NULL),
	 ('USIM5','Usiminas PNA',NULL,'60894730000105',NULL,'A','https://br.investing.com/equities/usiminas-pna','S',NULL,NULL),
	 ('USIM6','Usiminas PNB',NULL,'60894730000105',NULL,NULL,NULL,'N',NULL,NULL),
	 ('VVPR11','V2 Properties',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('VALE3','Vale ON',NULL,'33592510000154',NULL,'A','https://br.investing.com/equities/vale-on-n1','S',NULL,NULL),
	 ('VLOE34','Valero Energy BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('VLID3','Valid ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('VGIP11','Valora Cri Indice',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('VGIR11','VALORA RE III FII',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('CVBI11','Vbi Cri',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('VCJR11','Vectis Juros',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('VLJS11','Vector Queluz Lajes Corporativas',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('VERE11','Vereda',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('VERZ34','Verizon Communications BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('VIIA3','Via Varejo ON',NULL,'33041260065290',NULL,'A','https://br.investing.com/equities/via-varejo-sa','S',NULL,NULL),
	 ('VIGT11','Vinci Energia',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('VILG11','VINCI LOGISTICA FII',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('VINO11','Vinci Offices',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('VISA34','Visa BDR',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL),
	 ('VIVA3','Vivara',NULL,NULL,NULL,'A',NULL,'S',NULL,NULL),
	 ('VIVR3','Viver ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('VOTS11','Votorantim Securities Master',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('VULC3','Vulcabras ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/vulcabras-azaleia-sa','S',NULL,NULL),
	 ('WALM34','Wal Mart Stores BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('DISB34','Walt Disney BDR',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL),
	 ('WEGE3','Weg ON',NULL,'84429695000111',NULL,'A','https://br.investing.com/equities/weg-on-ej-nm','S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('WFCO34','Wells Fargo BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('WUNI34','Western Union BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('MWET3','Wetzel',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('MWET4','Wetzel PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('WHRL3','Whirlpool ON',NULL,'59105999000186',NULL,'A',NULL,'S',NULL,NULL),
	 ('WHRL4','Whirlpool PN',NULL,'59105999000186',NULL,'A',NULL,'S',NULL,NULL),
	 ('WSON33','Wilson Sons DR3',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('WIZS3','Wiz ON',NULL,'42278473000103',NULL,'A','https://br.investing.com/equities/fpc-par-corretora-de-seguros-sa','S',NULL,NULL),
	 ('WLMM3','WLM Industria e Comercio ON',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL),
	 ('WLMM4','WLM Industria e Comercio PN',NULL,NULL,NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('G1WW34','Ww Grainger',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('XRXB34','Xerox BDR',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('XPCI11','Xp Credito',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('XPHT11','XP HOTEIS FDO INV IMOB',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('XPHT12','XP HOTEIS FII',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('XPIE11','Xp Infra',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('XPLG11','XP Log FII',NULL,NULL,NULL,'F',NULL,'N',NULL,NULL),
	 ('XPPR11','Xp Prop',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('XPSF11','Xp Selection',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('YCHY11','Yaguara Capital High Yield',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('YDUQ3','Yduqs Part ON',NULL,NULL,NULL,'A','https://br.investing.com/equities/estacio-part-on-nm','S',NULL,NULL),
	 ('Z1BH34','Zimmer Biomet',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('AQLL11','Áquilla',NULL,NULL,NULL,NULL,NULL,'N',NULL,NULL),
	 ('S1PO34','Spotify Technology SA',NULL,NULL,NULL,'B',NULL,'S',NULL,NULL),
	 ('AIRB34','Airbnb INC',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('AIRB34','Airbnb INC',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('RAIZ4','Raizen SA',NULL,NULL,NULL,'A',NULL,'S',NULL,NULL),
	 ('INTB3','Intelbras S.A. Ind de Telec Eletronica Brasileira',NULL,NULL,NULL,'A',NULL,'S',NULL,NULL),
	 ('SBFG3','Centauro',NULL,'13217485000111',NULL,'A','https://br.investing.com/equities/grupo-sbf-sa','N',NULL,NULL),
	 ('AESB3','Aes Brasil Energia SA',NULL,'37663076000107',NULL,'A',NULL,'N',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('RECR11','FII REC Recebíveis Imobiliários',NULL,'28152272000126',NULL,'F','https://br.investing.com/equities/fi-imobiliario-ubs','S',NULL,NULL),
	 ('URPR11','Urca Prime Renda FII Closed Fund',NULL,'34508872000187',NULL,'F','https://br.investing.com/equities/urca-prime-renda-fii','S',NULL,NULL),
	 ('DEVA11','Devant Recebíveis Imobiliários Fundo de Investimento Imobiliário',NULL,'37087810000137',NULL,'F','https://br.investing.com/equities/devant-recebiveis-imobiliarios-fii','S',NULL,NULL),
	 ('GETT3','Getnet Adquirencia e Servicos para Meios de Pagamento SA',NULL,NULL,NULL,'A',NULL,'S',NULL,NULL),
	 ('XPBR31','XP inc',NULL,NULL,NULL,'B',NULL,'N',NULL,NULL),
	 ('VBBR3','VBBR3 - Vibra Energia S.A.',NULL,NULL,NULL,'A',NULL,'S',NULL,NULL),
	 ('DCRA11','Devant FI Cad Prod Agroindustriais',NULL,'42888360000111',NULL,'F',NULL,'S',NULL,NULL),
	 ('APTO11','Navi Residencial Fundo de Investimento Imobiliário',NULL,'42432327000182',NULL,'F',NULL,'S',NULL,NULL),
	 ('RZTR11 ','Riza Terrax ',NULL,'36501128000186',NULL,'F',NULL,'S',NULL,NULL),
	 ('CXSE3','Caixa Seguridade','Caixa Seguridade Participacoes SA','22543331000100',NULL,'A',NULL,'S',NULL,NULL);
INSERT INTO ativo (codigo,nome,nome_completo,cnpj,pais,tipo,caminho,seguindo,data_atualizacao,data_criacao) VALUES
	 ('AURE3','Auren Energia',NULL,'28594234000123',NULL,'A',NULL,'S',NULL,NULL),
	 ('SNAG11','Suno Agro','Suno Agro Fiagro Imobiliário','28152777000190',NULL,'F',NULL,'S',NULL,NULL),
	 ('SNAG13','Suno Agro','Suno Agro Fiagro Imobiliário','28152777000190',NULL,'F',NULL,'S',NULL,NULL),
	 ('SNAG12','Suno Agro','Suno Agro Fiagro Imobiliário','28152777000190',NULL,'F',NULL,'S',NULL,NULL),
	 ('TVRI11','BB PProgressivo','BB Progressivo II FII','14410722000129',NULL,'F','','S',NULL,NULL),
	 ('SNCI11','Suno Recebiveis Imobiliarios',NULL,'41076710000182',NULL,'F',NULL,'S',NULL,NULL),
	 ('VCRA11','Vectis Datagri CR Agric',NULL,'42502827000143',NULL,'F',NULL,'S',NULL,NULL),
	 ('RZAG11','O Fundo de Investimento nas Cadeias Produtivas Agroindustriais Riza Agro Fiagro Imobiliario',NULL,'40413979000144',NULL,'F',NULL,'S',NULL,NULL),
	 ('BTAL11','BTG Pactual Agro Logística',NULL,'36642244000115',NULL,'F',NULL,'S',NULL,NULL),
	 ('ALLD3','Allied Tecnologia SA',NULL,'20247322000147',NULL,'A',NULL,'S',NULL,NULL);