CREATE TABLE aporte (
    id INT AUTO_INCREMENT PRIMARY KEY,
    data_aporte DATE NOT NULL,
    valor DECIMAL(15,2) NOT NULL,
    origem VARCHAR(100) NOT NULL,
    destino VARCHAR(100) NOT NULL,
    data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);